name: Deploy application
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Double Entry
        uses: appleboy/ssh-action@v0.1.2
        env:
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: HASURA_GRAPHQL_DATABASE_URL
          script: |
            cd /var/www/double-entry-hasura
            pkill -9 hasura-engine
            git pull
            export HASURA_GRAPHQL_DATABASE_URL=$HASURA_GRAPHQL_DATABASE_URL
            sh -c '( ( hasura-engine --database-url "$HASURA_GRAPHQL_DATABASE_URL" serve --server-port 8081 --cors-domain "*" --admin-secret "$HASURA_GRAPHQL_ADMIN_SECRET" --enable-console ) & )'

