name: Deploy application
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Double Entry
        uses: appleboy/ssh-action@v0.1.2
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/double-entry-hasura
            pkill -9 hasura-engine
            git pull
            echo "$DATABASE_URL"
            hasura-engine --database-url "$DATABASE_URL" serve --server-port 8081 --cors-domain "*"
